package me.xiezefan.easyim.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHAT_ITEM.
 */
public class ChatItem {

    private Long id;
    private String msgId;
    private Long chatSessionId;
    private String targetId;
    private String type;
    private String fromId;
    private String content;
    private String extras;
    private String status;
    private Boolean isSelf;
    private Long createTime;

    public ChatItem() {
    }

    public ChatItem(Long id) {
        this.id = id;
    }

    public ChatItem(Long id, String msgId, Long chatSessionId, String targetId, String type, String fromId, String content, String extras, String status, Boolean isSelf, Long createTime) {
        this.id = id;
        this.msgId = msgId;
        this.chatSessionId = chatSessionId;
        this.targetId = targetId;
        this.type = type;
        this.fromId = fromId;
        this.content = content;
        this.extras = extras;
        this.status = status;
        this.isSelf = isSelf;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMsgId() {
        return msgId;
    }

    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    public Long getChatSessionId() {
        return chatSessionId;
    }

    public void setChatSessionId(Long chatSessionId) {
        this.chatSessionId = chatSessionId;
    }

    public String getTargetId() {
        return targetId;
    }

    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getFromId() {
        return fromId;
    }

    public void setFromId(String fromId) {
        this.fromId = fromId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getExtras() {
        return extras;
    }

    public void setExtras(String extras) {
        this.extras = extras;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Boolean getIsSelf() {
        return isSelf;
    }

    public void setIsSelf(Boolean isSelf) {
        this.isSelf = isSelf;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

}
