package me.xiezefan.easyim.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FRIEND_REQUEST.
 */
public class FriendRequest {

    private Long id;
    private String uid;
    private String username;
    private String nickname;
    private String displayName;
    private String avatar;
    private String reason;
    private String status;
    private Boolean isRead;
    private Long createTime;

    public FriendRequest() {
    }

    public FriendRequest(Long id) {
        this.id = id;
    }

    public FriendRequest(Long id, String uid, String username, String nickname, String displayName, String avatar, String reason, String status, Boolean isRead, Long createTime) {
        this.id = id;
        this.uid = uid;
        this.username = username;
        this.nickname = nickname;
        this.displayName = displayName;
        this.avatar = avatar;
        this.reason = reason;
        this.status = status;
        this.isRead = isRead;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

}
